//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaBrowser.WindowsPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaBrowser.WindowsPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to now playing.
        /// </summary>
        public static string AppBarAddToNowPlaying {
            get {
                return ResourceManager.GetString("AppBarAddToNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change profile.
        /// </summary>
        public static string AppBarChangeProfile {
            get {
                return ResourceManager.GetString("AppBarChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear now playing.
        /// </summary>
        public static string AppBarClearNowPlaying {
            get {
                return ResourceManager.GetString("AppBarClearNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete items.
        /// </summary>
        public static string AppBarDeleteItems {
            get {
                return ResourceManager.GetString("AppBarDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group by.
        /// </summary>
        public static string AppBarGroupBy {
            get {
                return ResourceManager.GetString("AppBarGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string AppBarLogin {
            get {
                return ResourceManager.GetString("AppBarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark as unwatched.
        /// </summary>
        public static string AppBarMarkAsUnwatched {
            get {
                return ResourceManager.GetString("AppBarMarkAsUnwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark as watched.
        /// </summary>
        public static string AppBarMarkAsWatched {
            get {
                return ResourceManager.GetString("AppBarMarkAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string AppBarNext {
            get {
                return ResourceManager.GetString("AppBarNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string AppBarNotifications {
            get {
                return ResourceManager.GetString("AppBarNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string AppBarNowPlaying {
            get {
                return ResourceManager.GetString("AppBarNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string AppBarPause {
            get {
                return ResourceManager.GetString("AppBarPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string AppBarPlay {
            get {
                return ResourceManager.GetString("AppBarPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play all.
        /// </summary>
        public static string AppBarPlayAll {
            get {
                return ResourceManager.GetString("AppBarPlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play all tracks.
        /// </summary>
        public static string AppBarPlayAllTracks {
            get {
                return ResourceManager.GetString("AppBarPlayAllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play items.
        /// </summary>
        public static string AppBarPlayItems {
            get {
                return ResourceManager.GetString("AppBarPlayItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play on....
        /// </summary>
        public static string AppBarPlayOn {
            get {
                return ResourceManager.GetString("AppBarPlayOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set poster as lock screen.
        /// </summary>
        public static string AppBarPosterLockscreen {
            get {
                return ResourceManager.GetString("AppBarPosterLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string AppBarPrevious {
            get {
                return ResourceManager.GetString("AppBarPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefresh {
            get {
                return ResourceManager.GetString("AppBarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh information.
        /// </summary>
        public static string AppBarRefreshInformation {
            get {
                return ResourceManager.GetString("AppBarRefreshInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote.
        /// </summary>
        public static string AppBarRemote {
            get {
                return ResourceManager.GetString("AppBarRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string AppBarResume {
            get {
                return ResourceManager.GetString("AppBarResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBarSearch {
            get {
                return ResourceManager.GetString("AppBarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select items.
        /// </summary>
        public static string AppBarSelectItems {
            get {
                return ResourceManager.GetString("AppBarSelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send logs.
        /// </summary>
        public static string AppBarSendLogs {
            get {
                return ResourceManager.GetString("AppBarSendLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not registered.
        /// </summary>
        public static string DeviceNotRegistered {
            get {
                return ResourceManager.GetString("DeviceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device registered.
        /// </summary>
        public static string DeviceRegistered {
            get {
                return ResourceManager.GetString("DeviceRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection details are invalid, please try again..
        /// </summary>
        public static string ErrorConnectionDetailsInvalid {
            get {
                return ResourceManager.GetString("ErrorConnectionDetailsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection details have been set, would you like to set them now?.
        /// </summary>
        public static string ErrorConnectionDetailsMessage {
            get {
                return ResourceManager.GetString("ErrorConnectionDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection details.
        /// </summary>
        public static string ErrorConnectionDetailsTitle {
            get {
                return ResourceManager.GetString("ErrorConnectionDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find your server..
        /// </summary>
        public static string ErrorCouldNotFindServer {
            get {
                return ResourceManager.GetString("ErrorCouldNotFindServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, it looks like this account has been disabled. We will now take you back to the login screen..
        /// </summary>
        public static string ErrorDisabledUser {
            get {
                return ResourceManager.GetString("ErrorDisabledUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign in.
        /// </summary>
        public static string ErrorDisabledUserTitle {
            get {
                return ResourceManager.GetString("ErrorDisabledUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading episode details.
        /// </summary>
        public static string ErrorEpisodeDetails {
            get {
                return ResourceManager.GetString("ErrorEpisodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting episodes.
        /// </summary>
        public static string ErrorEpisodes {
            get {
                return ResourceManager.GetString("ErrorEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run search.
        /// </summary>
        public static string ErrorFailedToSearch {
            get {
                return ResourceManager.GetString("ErrorFailedToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting data.
        /// </summary>
        public static string ErrorGettingData {
            get {
                return ResourceManager.GetString("ErrorGettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting extra information.
        /// </summary>
        public static string ErrorGettingExtraInfo {
            get {
                return ResourceManager.GetString("ErrorGettingExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the trailer information.
        /// </summary>
        public static string ErrorGettingTrailerDetails {
            get {
                return ResourceManager.GetString("ErrorGettingTrailerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your hostname is invalid, please make sure you don&apos;t have any spaces (for example) in it..
        /// </summary>
        public static string ErrorInvalidHostname {
            get {
                return ResourceManager.GetString("ErrorInvalidHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error making your changes.
        /// </summary>
        public static string ErrorMakingChanges {
            get {
                return ResourceManager.GetString("ErrorMakingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection settings, tap to set.
        /// </summary>
        public static string ErrorNoConnectionSettings {
            get {
                return ResourceManager.GetString("ErrorNoConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem updating this item, please try again later..
        /// </summary>
        public static string ErrorProblemUpdatingItem {
            get {
                return ResourceManager.GetString("ErrorProblemUpdatingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting recent items.
        /// </summary>
        public static string ErrorRecentItems {
            get {
                return ResourceManager.GetString("ErrorRecentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting seasons.
        /// </summary>
        public static string ErrorSeasons {
            get {
                return ResourceManager.GetString("ErrorSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to sign you in at this time, this could be due to an incorrect username/password, or your account has been disabled..
        /// </summary>
        public static string ErrorUnableToSignIn {
            get {
                return ResourceManager.GetString("ErrorUnableToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login unsuccessful.
        /// </summary>
        public static string ErrorUnableToSignInTitle {
            get {
                return ResourceManager.GetString("ErrorUnableToSignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a client.
        /// </summary>
        public static string HeaderChooseClient {
            get {
                return ResourceManager.GetString("HeaderChooseClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default grouping.
        /// </summary>
        public static string HeaderDefaultGrouping {
            get {
                return ResourceManager.GetString("HeaderDefaultGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From collection (where applicable):.
        /// </summary>
        public static string HeaderFromCollection {
            get {
                return ResourceManager.GetString("HeaderFromCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string LabelActor {
            get {
                return ResourceManager.GetString("LabelActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string LabelAdd {
            get {
                return ResourceManager.GetString("LabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favourites.
        /// </summary>
        public static string LabelAddToFavourites {
            get {
                return ResourceManager.GetString("LabelAddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        public static string LabelAlbums {
            get {
                return ResourceManager.GetString("LabelAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string LabelAnHourAgo {
            get {
                return ResourceManager.GetString("LabelAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string LabelArtists {
            get {
                return ResourceManager.GetString("LabelArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bio.
        /// </summary>
        public static string LabelBio {
            get {
                return ResourceManager.GetString("LabelBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boxsets.
        /// </summary>
        public static string LabelBoxsets {
            get {
                return ResourceManager.GetString("LabelBoxsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cast + crew.
        /// </summary>
        public static string LabelCastCrew {
            get {
                return ResourceManager.GetString("LabelCastCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chapters.
        /// </summary>
        public static string LabelChapters {
            get {
                return ResourceManager.GetString("LabelChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen collage.
        /// </summary>
        public static string LabelCollage {
            get {
                return ResourceManager.GetString("LabelCollage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string LabelConnect {
            get {
                return ResourceManager.GetString("LabelConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection.
        /// </summary>
        public static string LabelConnection {
            get {
                return ResourceManager.GetString("LabelConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the connection details in to point to the computer running Media Browser 3. Then simply test them to confirm..
        /// </summary>
        public static string LabelConnectionDetails {
            get {
                return ResourceManager.GetString("LabelConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Changing the hostname will remove any saved profiles..
        /// </summary>
        public static string LabelConnectionWarning {
            get {
                return ResourceManager.GetString("LabelConnectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string LabelDaysAgo {
            get {
                return ResourceManager.GetString("LabelDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default lock screen.
        /// </summary>
        public static string LabelDefaultLockScreen {
            get {
                return ResourceManager.GetString("LabelDefaultLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string LabelDetails {
            get {
                return ResourceManager.GetString("LabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string LabelDirector {
            get {
                return ResourceManager.GetString("LabelDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display random backdrop images on the back of the tile.
        /// </summary>
        public static string LabelDisplayRandomImages {
            get {
                return ResourceManager.GetString("LabelDisplayRandomImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string LabelEpisode {
            get {
                return ResourceManager.GetString("LabelEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find server.
        /// </summary>
        public static string LabelFindServer {
            get {
                return ResourceManager.GetString("LabelFindServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the Media Browser server is configured, make sure it&apos;s accessible from where you are, whether that&apos;s being on your local wireless network, or an external static address..
        /// </summary>
        public static string LabelFirstRunAccessible {
            get {
                return ResourceManager.GetString("LabelFirstRunAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re happy with what you&apos;ve configured, click the settings button and enter your server&apos;s details, else you can just quit the app from here..
        /// </summary>
        public static string LabelFirstRunHappyConfiguration {
            get {
                return ResourceManager.GetString("LabelFirstRunHappyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before we can get started though, you need to make sure you&apos;re running the Media Browser server..
        /// </summary>
        public static string LabelFirstRunServerInfo {
            get {
                return ResourceManager.GetString("LabelFirstRunServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string LabelGeneral {
            get {
                return ResourceManager.GetString("LabelGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genres.
        /// </summary>
        public static string LabelGenres {
            get {
                return ResourceManager.GetString("LabelGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname:.
        /// </summary>
        public static string LabelHostname {
            get {
                return ResourceManager.GetString("LabelHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string LabelHoursAgo {
            get {
                return ResourceManager.GetString("LabelHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable enhanced images (if installed on the server).
        /// </summary>
        public static string LabelImageEnhancers {
            get {
                return ResourceManager.GetString("LabelImageEnhancers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See film on imdb.
        /// </summary>
        public static string LabelImdb {
            get {
                return ResourceManager.GetString("LabelImdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Browser is the current lock screen provider.
        /// </summary>
        public static string LabelIsLockScreenProvider {
            get {
                return ResourceManager.GetString("LabelIsLockScreenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Browser is not the lock screen provider.
        /// </summary>
        public static string LabelIsNotLockScreenProvider {
            get {
                return ResourceManager.GetString("LabelIsNotLockScreenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just show the list of items, not a media folder view.
        /// </summary>
        public static string LabelJustShowList {
            get {
                return ResourceManager.GetString("LabelJustShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest unseen.
        /// </summary>
        public static string LabelLatestUnseen {
            get {
                return ResourceManager.GetString("LabelLatestUnseen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live TV.
        /// </summary>
        public static string LabelLiveTv {
            get {
                return ResourceManager.GetString("LabelLiveTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen.
        /// </summary>
        public static string LabelLockScreen {
            get {
                return ResourceManager.GetString("LabelLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen settings.
        /// </summary>
        public static string LabelLockScreenSettinsg {
            get {
                return ResourceManager.GetString("LabelLockScreenSettinsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LabelLogIn {
            get {
                return ResourceManager.GetString("LabelLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make us the lock screen provider.
        /// </summary>
        public static string LabelMakeLockScreenProvider {
            get {
                return ResourceManager.GetString("LabelMakeLockScreenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually login.
        /// </summary>
        public static string LabelManuallyLogin {
            get {
                return ResourceManager.GetString("LabelManuallyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string LabelMinutesAgo {
            get {
                return ResourceManager.GetString("LabelMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show missing episodes.
        /// </summary>
        public static string LabelMissingEpisodes {
            get {
                return ResourceManager.GetString("LabelMissingEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string LabelMonthsAgo {
            get {
                return ResourceManager.GetString("LabelMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string LabelMovies {
            get {
                return ResourceManager.GetString("LabelMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string LabelMusic {
            get {
                return ResourceManager.GetString("LabelMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next up.
        /// </summary>
        public static string LabelNextUp {
            get {
                return ResourceManager.GetString("LabelNextUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string LabelNo {
            get {
                return ResourceManager.GetString("LabelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No episodes to show.
        /// </summary>
        public static string LabelNoEpisodes {
            get {
                return ResourceManager.GetString("LabelNoEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folders found.
        /// </summary>
        public static string LabelNoFoldersFound {
            get {
                return ResourceManager.GetString("LabelNoFoldersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string LabelNone {
            get {
                return ResourceManager.GetString("LabelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seasons found.
        /// </summary>
        public static string LabelNoSeasonsFound {
            get {
                return ResourceManager.GetString("LabelNoSeasonsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing in your playlist.
        /// </summary>
        public static string LabelNothingInPlaylist {
            get {
                return ResourceManager.GetString("LabelNothingInPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string LabelNotifications {
            get {
                return ResourceManager.GetString("LabelNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string LabelNowPlaying {
            get {
                return ResourceManager.GetString("LabelNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute ago.
        /// </summary>
        public static string LabelOneMinuteAgo {
            get {
                return ResourceManager.GetString("LabelOneMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month ago.
        /// </summary>
        public static string LabelOneMonthAgo {
            get {
                return ResourceManager.GetString("LabelOneMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second ago.
        /// </summary>
        public static string LabelOneSecondAgo {
            get {
                return ResourceManager.GetString("LabelOneSecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string LabelOther {
            get {
                return ResourceManager.GetString("LabelOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview.
        /// </summary>
        public static string LabelOverview {
            get {
                return ResourceManager.GetString("LabelOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password:.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poster.
        /// </summary>
        public static string LabelPoster {
            get {
                return ResourceManager.GetString("LabelPoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        public static string LabelProducer {
            get {
                return ResourceManager.GetString("LabelProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string LabelProfile {
            get {
                return ResourceManager.GetString("LabelProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not listed?.
        /// </summary>
        public static string LabelProfileNotListed {
            get {
                return ResourceManager.GetString("LabelProfileNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profiles.
        /// </summary>
        public static string LabelProfiles {
            get {
                return ResourceManager.GetString("LabelProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quit.
        /// </summary>
        public static string LabelQuit {
            get {
                return ResourceManager.GetString("LabelQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Items.
        /// </summary>
        public static string LabelRandomItems {
            get {
                return ResourceManager.GetString("LabelRandomItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random pictures from collection.
        /// </summary>
        public static string LabelRandomPictures {
            get {
                return ResourceManager.GetString("LabelRandomPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string LabelRating {
            get {
                return ResourceManager.GetString("LabelRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string LabelRecent {
            get {
                return ResourceManager.GetString("LabelRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released in.
        /// </summary>
        public static string LabelReleasedIn {
            get {
                return ResourceManager.GetString("LabelReleasedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string LabelRemote {
            get {
                return ResourceManager.GetString("LabelRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string LabelRemove {
            get {
                return ResourceManager.GetString("LabelRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running time:.
        /// </summary>
        public static string LabelRunningTime {
            get {
                return ResourceManager.GetString("LabelRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seasons.
        /// </summary>
        public static string LabelSeasons {
            get {
                return ResourceManager.GetString("LabelSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string LabelSecondsAgo {
            get {
                return ResourceManager.GetString("LabelSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string LabelSeries {
            get {
                return ResourceManager.GetString("LabelSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all items....
        /// </summary>
        public static string LabelShowAllItems {
            get {
                return ResourceManager.GetString("LabelShowAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows.
        /// </summary>
        public static string LabelShows {
            get {
                return ResourceManager.GetString("LabelShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show trailers in recent items.
        /// </summary>
        public static string LabelShowTrailers {
            get {
                return ResourceManager.GetString("LabelShowTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single poster.
        /// </summary>
        public static string LabelSinglePoster {
            get {
                return ResourceManager.GetString("LabelSinglePoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        public static string LabelSongs {
            get {
                return ResourceManager.GetString("LabelSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tile.
        /// </summary>
        public static string LabelTile {
            get {
                return ResourceManager.GetString("LabelTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To show off some of the great artwork available for the media you have, the tile will use some of that artwork, here you can choose how that tile will look.
        /// </summary>
        public static string LabelTileBackInformation {
            get {
                return ResourceManager.GetString("LabelTileBackInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trailers.
        /// </summary>
        public static string LabelTrailers {
            get {
                return ResourceManager.GetString("LabelTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string LabelTv {
            get {
                return ResourceManager.GetString("LabelTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show unaired episodes.
        /// </summary>
        public static string LabelUnairedEpisodes {
            get {
                return ResourceManager.GetString("LabelUnairedEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplayed:.
        /// </summary>
        public static string LabelUnplayedItems {
            get {
                return ResourceManager.GetString("LabelUnplayedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unwatched:.
        /// </summary>
        public static string LabelUnwatched {
            get {
                return ResourceManager.GetString("LabelUnwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username:.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string LabelViews {
            get {
                return ResourceManager.GetString("LabelViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Media Browser for Windows Phone. This app will allow you to browse your media collection, stream it to your phone and remotely control any of the controllable Media Browser clients..
        /// </summary>
        public static string LabelWelcomeText {
            get {
                return ResourceManager.GetString("LabelWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Media Browser for Windows Phone. This app will allow you to browse your media collection and remotely control any of the controllable Media Browser clients..
        /// </summary>
        public static string LabelWelcomeTextPhone7 {
            get {
                return ResourceManager.GetString("LabelWelcomeTextPhone7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string LabelWriter {
            get {
                return ResourceManager.GetString("LabelWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string LabelYes {
            get {
                return ResourceManager.GetString("LabelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string LabelYesterday {
            get {
                return ResourceManager.GetString("LabelYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play from.
        /// </summary>
        public static string MenuPlayFrom {
            get {
                return ResourceManager.GetString("MenuPlayFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play from on.
        /// </summary>
        public static string MenuPlayFromOn {
            get {
                return ResourceManager.GetString("MenuPlayFromOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MessageAreYouSureTitle {
            get {
                return ResourceManager.GetString("MessageAreYouSureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to unpin this tile?.
        /// </summary>
        public static string MessageBoxUnpinText {
            get {
                return ResourceManager.GetString("MessageBoxUnpinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear your playlist?.
        /// </summary>
        public static string MessageClearPlayList {
            get {
                return ResourceManager.GetString("MessageClearPlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete these items? This cannot be undone..
        /// </summary>
        public static string MessageDeletePlaylistItems {
            get {
                return ResourceManager.GetString("MessageDeletePlaylistItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        public static string MessageExperimentalTitle {
            get {
                return ResourceManager.GetString("MessageExperimentalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing this type of video is currently experimental, results may vary, do you wish to continue?.
        /// </summary>
        public static string MessageExperimentalVideo {
            get {
                return ResourceManager.GetString("MessageExperimentalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tracks added successfully..
        /// </summary>
        public static string MessageTracksAddedSuccessfully {
            get {
                return ResourceManager.GetString("MessageTracksAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more....
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        public static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to production year.
        /// </summary>
        public static string ProductionYear {
            get {
                return ResourceManager.GetString("ProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favourites.
        /// </summary>
        public static string RemoveFromFavouritesFull {
            get {
                return ResourceManager.GetString("RemoveFromFavouritesFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-GB.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to favourites....
        /// </summary>
        public static string SysTrayAddingToFavourites {
            get {
                return ResourceManager.GetString("SysTrayAddingToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string SysTrayAuthenticating {
            get {
                return ResourceManager.GetString("SysTrayAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking collection....
        /// </summary>
        public static string SysTrayCheckingCollection {
            get {
                return ResourceManager.GetString("SysTrayCheckingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection....
        /// </summary>
        public static string SysTrayCheckingConnection {
            get {
                return ResourceManager.GetString("SysTrayCheckingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to find your server....
        /// </summary>
        public static string SysTrayFindingServer {
            get {
                return ResourceManager.GetString("SysTrayFindingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting albums....
        /// </summary>
        public static string SysTrayGettingAlbums {
            get {
                return ResourceManager.GetString("SysTrayGettingAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting album tracks....
        /// </summary>
        public static string SysTrayGettingAlbumTracks {
            get {
                return ResourceManager.GetString("SysTrayGettingAlbumTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all tracks....
        /// </summary>
        public static string SysTrayGettingAllTracks {
            get {
                return ResourceManager.GetString("SysTrayGettingAllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting artists....
        /// </summary>
        public static string SysTrayGettingArtists {
            get {
                return ResourceManager.GetString("SysTrayGettingArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting artist tracks....
        /// </summary>
        public static string SysTrayGettingArtistTracks {
            get {
                return ResourceManager.GetString("SysTrayGettingArtistTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting boxsets....
        /// </summary>
        public static string SysTrayGettingBoxsets {
            get {
                return ResourceManager.GetString("SysTrayGettingBoxsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting details....
        /// </summary>
        public static string SysTrayGettingDetails {
            get {
                return ResourceManager.GetString("SysTrayGettingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting episode details....
        /// </summary>
        public static string SysTrayGettingEpisodeDetails {
            get {
                return ResourceManager.GetString("SysTrayGettingEpisodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting episodes....
        /// </summary>
        public static string SysTrayGettingEpisodes {
            get {
                return ResourceManager.GetString("SysTrayGettingEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting favourites....
        /// </summary>
        public static string SysTrayGettingFavourites {
            get {
                return ResourceManager.GetString("SysTrayGettingFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting genres....
        /// </summary>
        public static string SysTrayGettingGenres {
            get {
                return ResourceManager.GetString("SysTrayGettingGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting genre tracks....
        /// </summary>
        public static string SysTrayGettingGenreTracks {
            get {
                return ResourceManager.GetString("SysTrayGettingGenreTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting items....
        /// </summary>
        public static string SysTrayGettingItems {
            get {
                return ResourceManager.GetString("SysTrayGettingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting movie information....
        /// </summary>
        public static string SysTrayGettingMovieInfo {
            get {
                return ResourceManager.GetString("SysTrayGettingMovieInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting movies....
        /// </summary>
        public static string SysTrayGettingMovies {
            get {
                return ResourceManager.GetString("SysTrayGettingMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting next up items....
        /// </summary>
        public static string SysTrayGettingNextUp {
            get {
                return ResourceManager.GetString("SysTrayGettingNextUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting notifications....
        /// </summary>
        public static string SysTrayGettingNotifications {
            get {
                return ResourceManager.GetString("SysTrayGettingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting profiles....
        /// </summary>
        public static string SysTrayGettingProfiles {
            get {
                return ResourceManager.GetString("SysTrayGettingProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting recent items....
        /// </summary>
        public static string SysTrayGettingRecentItems {
            get {
                return ResourceManager.GetString("SysTrayGettingRecentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting server details....
        /// </summary>
        public static string SysTrayGettingServerDetails {
            get {
                return ResourceManager.GetString("SysTrayGettingServerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting show information....
        /// </summary>
        public static string SysTrayGettingShowInformation {
            get {
                return ResourceManager.GetString("SysTrayGettingShowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting TV shows....
        /// </summary>
        public static string SysTrayGettingShows {
            get {
                return ResourceManager.GetString("SysTrayGettingShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting songs....
        /// </summary>
        public static string SysTrayGettingSongs {
            get {
                return ResourceManager.GetString("SysTrayGettingSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting tracks....
        /// </summary>
        public static string SysTrayGettingTracks {
            get {
                return ResourceManager.GetString("SysTrayGettingTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting trailer details....
        /// </summary>
        public static string SysTrayGettingTrailerDetails {
            get {
                return ResourceManager.GetString("SysTrayGettingTrailerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting latest unwatched items....
        /// </summary>
        public static string SysTrayGettingUnwatchedItems {
            get {
                return ResourceManager.GetString("SysTrayGettingUnwatchedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading collections....
        /// </summary>
        public static string SysTrayLoadingCollections {
            get {
                return ResourceManager.GetString("SysTrayLoadingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings....
        /// </summary>
        public static string SysTrayLoadingSettings {
            get {
                return ResourceManager.GetString("SysTrayLoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering device....
        /// </summary>
        public static string SysTrayRegisteringDevice {
            get {
                return ResourceManager.GetString("SysTrayRegisteringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-grouping....
        /// </summary>
        public static string SysTrayRegrouping {
            get {
                return ResourceManager.GetString("SysTrayRegrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string SysTraySearching {
            get {
                return ResourceManager.GetString("SysTraySearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistering device....
        /// </summary>
        public static string SysTrayUnregisteringDevice {
            get {
                return ResourceManager.GetString("SysTrayUnregisteringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In trial mode you can only play one video per day. Please try this tomorrow or purchase the full version..
        /// </summary>
        public static string TrialVideoMessage {
            get {
                return ResourceManager.GetString("TrialVideoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s recent items.
        /// </summary>
        public static string TvShowRecentItemsTitle {
            get {
                return ResourceManager.GetString("TvShowRecentItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter a username.
        /// </summary>
        public static string WatermarkEnterUsername {
            get {
                return ResourceManager.GetString("WatermarkEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter a password.
        /// </summary>
        public static string WatermarkPassword {
            get {
                return ResourceManager.GetString("WatermarkPassword", resourceCulture);
            }
        }
    }
}
