//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaBrowser.WindowsPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaBrowser.WindowsPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddFavourite {
            get {
                return ResourceManager.GetString("AddFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favourites.
        /// </summary>
        public static string AddToFavouritesFull {
            get {
                return ResourceManager.GetString("AddToFavouritesFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not registered.
        /// </summary>
        public static string DeviceNotRegistered {
            get {
                return ResourceManager.GetString("DeviceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device registered.
        /// </summary>
        public static string DeviceRegistered {
            get {
                return ResourceManager.GetString("DeviceRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection details are invalid, please try again..
        /// </summary>
        public static string ErrorConnectionDetailsInvalid {
            get {
                return ResourceManager.GetString("ErrorConnectionDetailsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find your server..
        /// </summary>
        public static string ErrorCouldNotFindServer {
            get {
                return ResourceManager.GetString("ErrorCouldNotFindServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading episode details.
        /// </summary>
        public static string ErrorEpisodeDetails {
            get {
                return ResourceManager.GetString("ErrorEpisodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting episodes.
        /// </summary>
        public static string ErrorEpisodes {
            get {
                return ResourceManager.GetString("ErrorEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting data.
        /// </summary>
        public static string ErrorGettingData {
            get {
                return ResourceManager.GetString("ErrorGettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting extra information.
        /// </summary>
        public static string ErrorGettingExtraInfo {
            get {
                return ResourceManager.GetString("ErrorGettingExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection settings, tap to set.
        /// </summary>
        public static string ErrorNoConnectionSettings {
            get {
                return ResourceManager.GetString("ErrorNoConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting recent items.
        /// </summary>
        public static string ErrorRecentItems {
            get {
                return ResourceManager.GetString("ErrorRecentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting seasons.
        /// </summary>
        public static string ErrorSeasons {
            get {
                return ResourceManager.GetString("ErrorSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favourites.
        /// </summary>
        public static string LabelAddToFavourites {
            get {
                return ResourceManager.GetString("LabelAddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change profile.
        /// </summary>
        public static string MainAppBarChangeProfile {
            get {
                return ResourceManager.GetString("MainAppBarChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh information.
        /// </summary>
        public static string MainAppBarRefreshInformation {
            get {
                return ResourceManager.GetString("MainAppBarRefreshInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MessageBoxHeaderAreYouSure {
            get {
                return ResourceManager.GetString("MessageBoxHeaderAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to unpin this tile?.
        /// </summary>
        public static string MessageBoxUnpinText {
            get {
                return ResourceManager.GetString("MessageBoxUnpinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more....
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        public static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to production year.
        /// </summary>
        public static string ProductionYear {
            get {
                return ResourceManager.GetString("ProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string RemoveFavourite {
            get {
                return ResourceManager.GetString("RemoveFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favourites.
        /// </summary>
        public static string RemoveFromFavouritesFull {
            get {
                return ResourceManager.GetString("RemoveFromFavouritesFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-GB.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all items....
        /// </summary>
        public static string ShowAllItems {
            get {
                return ResourceManager.GetString("ShowAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string SysTrayAuthenticating {
            get {
                return ResourceManager.GetString("SysTrayAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking collection....
        /// </summary>
        public static string SysTrayCheckingCollection {
            get {
                return ResourceManager.GetString("SysTrayCheckingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection....
        /// </summary>
        public static string SysTrayCheckingConnection {
            get {
                return ResourceManager.GetString("SysTrayCheckingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting albums....
        /// </summary>
        public static string SysTrayGettingAlbums {
            get {
                return ResourceManager.GetString("SysTrayGettingAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting episode details....
        /// </summary>
        public static string SysTrayGettingEpisodeDetails {
            get {
                return ResourceManager.GetString("SysTrayGettingEpisodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting episodes....
        /// </summary>
        public static string SysTrayGettingEpisodes {
            get {
                return ResourceManager.GetString("SysTrayGettingEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting favourites....
        /// </summary>
        public static string SysTrayGettingFavourites {
            get {
                return ResourceManager.GetString("SysTrayGettingFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting items....
        /// </summary>
        public static string SysTrayGettingItems {
            get {
                return ResourceManager.GetString("SysTrayGettingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting movie information....
        /// </summary>
        public static string SysTrayGettingMovieInfo {
            get {
                return ResourceManager.GetString("SysTrayGettingMovieInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting profiles....
        /// </summary>
        public static string SysTrayGettingProfiles {
            get {
                return ResourceManager.GetString("SysTrayGettingProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting recent items....
        /// </summary>
        public static string SysTrayGettingRecentItems {
            get {
                return ResourceManager.GetString("SysTrayGettingRecentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting server details....
        /// </summary>
        public static string SysTrayGettingServerDetails {
            get {
                return ResourceManager.GetString("SysTrayGettingServerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting show information....
        /// </summary>
        public static string SysTrayGettingShowInformation {
            get {
                return ResourceManager.GetString("SysTrayGettingShowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading collections....
        /// </summary>
        public static string SysTrayLoadingCollections {
            get {
                return ResourceManager.GetString("SysTrayLoadingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings....
        /// </summary>
        public static string SysTrayLoadingSettings {
            get {
                return ResourceManager.GetString("SysTrayLoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering device....
        /// </summary>
        public static string SysTrayRegisteringDevice {
            get {
                return ResourceManager.GetString("SysTrayRegisteringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-grouping....
        /// </summary>
        public static string SysTrayRegrouping {
            get {
                return ResourceManager.GetString("SysTrayRegrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistering device....
        /// </summary>
        public static string SysTrayUnregisteringDevice {
            get {
                return ResourceManager.GetString("SysTrayUnregisteringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s recent items.
        /// </summary>
        public static string TvShowRecentItemsTitle {
            get {
                return ResourceManager.GetString("TvShowRecentItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
    }
}
